# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    trusted_proxies: '192.0.0.1,10.0.0.0/8'
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix' ]

    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true
    error_controller: Surfnet\AzureMfa\Infrastructure\Controller\ExceptionController::showAction
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        # SameSite is set to none. As we must allow receiving a session cookie from the (trusted)
        # remote Azure MFA IdP's
        cookie_samesite: 'none'
    assets: ~
    esi: false
    fragments: false
    php_errors:
        log: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
        profiler:
            collect: false
