parameters:
  institution_configuration: # Configuration identifier
    data: # Root node
      institutions:
        institution-a.example.com:
          destination: 'https://adfs.stepup.example.com/adfs/ls/'
          email_domains:
            - 'stepup.example.com'
            - '*.example.com' # Wildcards are allowed
        harting-college.nl:
          destination: 'https://adfs.harting-college.nl/adfs/ls/'
          email_domains: ['harting-college.nl']
