twig:
    exception_controller: Surfnet\AzureMfa\Infrastructure\Controller\ExceptionController::showAction
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
