twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        global_view_parameters: "@Surfnet\\AzureMfa\\Infrastructure\\Twig\\GlobalViewParameters"
    form_themes: [ 'bootstrap_4_layout.html.twig' ]
