controllers:
    resource: ../../src/Surfnet/AzureMfa/Infrastructure/Controller/
    type: attribute

open_conext_monitor:
    resource: "@OpenConextMonitorBundle/src/Controller"
    type: attribute
    prefix: /
