monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: main_syslog
            bubble: false
        main_syslog:
            type: syslog
            ident: stepup-azure-mfa
            facility: user
        console:
            type: console
            process_psr_3_messages: false
