monolog:
    handlers:
        prod-signaler:
            type: fingers_crossed
            action_level: ERROR
            passthru_level: NOTICE # this means that all message of level NOTICE or higher are always logged
            handler: main_syslog
            bubble: false # if we handle it, nothing else should
        main_syslog:
            type: syslog
            ident: stepup-azure-mfa
            facility: user
            formatter: surfnet_stepup.monolog.json_formatter
        console:
            type: console
            process_psr_3_messages: false

framework:
    php_errors:
        log: 24575 # change error reporting level to: E_ALL & ~E_DEPRECATED (32767 - 8192 = 24575)