# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: nl

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Surfnet\AzureMfa\:
        resource: '../src/Surfnet/AzureMfa/*'

    Surfnet\AzureMfa\Infrastructure\:
        resource: '../src/Surfnet/AzureMfa/Infrastructure/*'
        exclude: '../src/Surfnet/AzureMfa/Infrastructure/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Surfnet\AzureMfa\Infrastructure\Controller\:
        resource: '../src/Surfnet/AzureMfa/Infrastructure/Controller/*'
        tags: ['controller.service_arguments']

    Surfnet\AzureMfa\Infrastructure\Institution\ConfigurationValidator:
        arguments:
            $configuration: '%institution_configuration%'

    Dev\Mock\MockConfiguration:
        arguments:
            $identityProviderEntityId: 'https://azure-mfa.stepup.example.com/mock/idp/metadata'
            $serviceProviderEntityId: 'https://azure-mfa.stepup.example.com/saml/metadata'
            $privateKeyPath: '%saml_idp_privatekey%'
            $publicCertPath: '%saml_idp_publickey%'

    Surfnet\AzureMfa\Infrastructure\Repository\UserFileRepository:
        arguments:
            $userRepositoryPath: '%kernel.root_dir%/../../../../var/userRepository-%kernel.environment%.json'