# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: nl_NL

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Surfnet\AzureMfa\:
        resource: '../src/Surfnet/AzureMfa/*'

    Surfnet\AzureMfa\Infrastructure\:
        resource: '../src/Surfnet/AzureMfa/Infrastructure/*'
        exclude: '../src/Surfnet/AzureMfa/Infrastructure/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Surfnet\AzureMfa\Infrastructure\Controller\:
        resource: '../src/Surfnet/AzureMfa/Infrastructure/Controller/*'
        tags: ['controller.service_arguments']

    Surfnet\AzureMfa\Infrastructure\Institution\ConfigurationValidator:
        arguments:
            $configuration: '%institution_configuration%'

    Surfnet\AzureMfa\Infrastructure\Twig\GlobalViewParameters:
        arguments:
            $locales: '%locales%'
            $supportUrl: '%support_url%'
            $supportEmail: '%support_email%'
