---

# Install plantuml

- name: Install graphviz
  yum:
    name: graphviz
    state: present

- stat:
    path: /usr/bin/plantuml
  register: stplantuml

- name: Download plantuml.jar
  get_url:
    url:  http://sourceforge.net/projects/plantuml/files/plantuml.jar/download
    dest: /usr/share/plantuml.jar
    mode: u=rw,g=rw,o=rw
  when: stplantuml.stat.islnk is not defined

- name: Create binary link
  template:
    src: 'plantuml.sh.j2'
    dest: '/usr/bin/plantuml'
    mode: 'u=xrw,g=xrw,o=rwx'
  when: stplantuml.stat.islnk is not defined
